
env:
  JULIA_VERSION: "1.10.9"
  JULIA_MINOR_VERSION: "1.10"
  TARTARUS_HOME: "/storage5/buildkite-agent"
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
  JULIA_NUM_PRECOMPILE_TASKS: 8
  JULIA_NUM_THREADS: 8
  CUDA_VISIBLE_DEVICES: "2" # Device for building ClimaOcean docs

steps:
  - label: "initialize"
    key: "init"
    env:
      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "init"
      JULIA_BINDIR: "$TARTARUS_HOME/julia-$JULIA_VERSION/bin"
      TMPDIR: "$TARTARUS_HOME/tmp"
    command:
      - "echo '--- Instantiate project'"
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes -O0 --project -e 'using Pkg; Pkg.instantiate(; verbose=true); Pkg.precompile(; strict=true)'"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes -O0 --project -e 'using CUDA; CUDA.precompile_runtime()'"
    agents:
      queue: ClimaOcean-docs

  - wait

  - label: "Run documentation"
    key: "build_documentation"
    commands:
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes -O0 --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.add(url=\"https://github.com/CliMA/Oceananigans.jl\", rev=\"ss/fix-zstar-bc\"); Pkg.instantiate()'"
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes -O0 --project=docs/ docs/make.jl"
    agents:
      queue: ClimaOcean-docs

    env:
      TMPDIR: "$TARTARUS_HOME/tmp"
      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      JULIA_DEBUG: "Documenter"
      # This environment variable is needed to avoid SSL verification errors when Downloads.jl
      # tries to download the bathymetry data. It should not be required so we need to fix our certificates
      # and remove this environment variable. ref: https://github.com/JuliaLang/Downloads.jl/issues/97
      JULIA_SSL_NO_VERIFY: "**"

    timeout_in_minutes: 1440

  - wait: ~
    continue_on_failure: true
