agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_05_27
  slurm_time: 48:00:00

timeout_in_minutes: 1440

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0

steps:
  - label: "initialize"
    key: "init"
    command:
      - "echo '--- Instantiate project'"
      - "julia --project -e 'using Pkg; Pkg.instantiate(; verbose=true); Pkg.precompile(; strict=true)'"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"

    agents:
      slurm_mem: 120G
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: "Run documentation"
    key: "build_documentation"
    commands:
      - "julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'"
      - "julia --color=yes --project=docs/ docs/make.jl"

    agents:
      slurm_mem: 120G
      slurm_gpus: 1
      slurm_cpus_per_task: 8
      slurm_ntasks: 1
      slurm_gpus_per_task: 1
      slurm_time: 48:00:00
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
    timeout_in_minutes: 1440

  - wait: ~
    continue_on_failure: true
