agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_05_27

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_NUM_PRECOMPILE_TASKS: 8

steps:
  - label: "initialize"
    key: "init"
    command:
      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(; verbose=true)'"
      - echo "--- Precompile project"
      - "julia --project -e 'using Pkg; Pkg.precompile(; strict=true)'"

    agents:
      slurm_mem: 120G
      slurm_gpus: 1
      slurm_cpus_per_task: 8

  - wait

  - label: "Run documentation"
    key: "build_documentation"
    commands:
      - "julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate()'"
      - "julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --color=yes --project=docs/ -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --color=yes --project=docs/ docs/make.jl"

    agents:
      slurm_mem: 120G
      slurm_gpus: 1
      slurm_cpus_per_task: 8
      slurm_ntasks: 1
      slurm_gpus_per_task: 1
      slurm_time: 48:00:00

    env:
      JULIA_DEBUG: "Documenter"
      # This environment variable is needed to avoid SSL verification errors when Downloads.jl 
      # tries to download the bathymetry data. It should not be required so we need to fix our certificates.
      # and remove this environment variable. ref: https://github.com/JuliaLang/Downloads.jl/issues/97
      JULIA_SSL_NO_VERIFY: "**" 

    timeout_in_minutes: 1440

  - wait: ~
    continue_on_failure: true
