agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_05_27

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_DEBUG: "Documenter"
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0

steps:
  - label: "initialize"
    key: "init"
    command:
      - "echo '--- Instantiate project'"
      - "julia --project -e 'using Pkg; Pkg.instantiate(; verbose=true); Pkg.precompile(; strict=true)'"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"

    agents:
      slurm_mem: 32G
      slurm_gpus: 1
      slurm_cpus_per_task: 8
      slurm_ntasks: 1
      slurm_gpus_per_task: 1
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: "CPU JRA55 tests"
    key: "cpu_jra55_tests"
    env:
      TEST_GROUP: "jra55"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 32G
      slurm_cpus_per_task: 8
      slurm_ntasks: 1

  - label: "CPU ECCO tests"
    key: "cpu_ecco_tests"
    env:
      TEST_GROUP: "ecco"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 32G
      slurm_cpus_per_task: 8
      slurm_ntasks: 1

  - label: "CPU surface flux tests"
    key: "cpu_fluxes_tests"
    env:
      TEST_GROUP: "fluxes"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 32G
      slurm_cpus_per_task: 8
      slurm_ntasks: 1

  - label: "CPU bathymetry tests"
    key: "cpu_bathymetry_tests"
    env:
      TEST_GROUP: "bathymetry"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 32G
      slurm_cpus_per_task: 8
      slurm_ntasks: 1

  - label: "GPU JRA55 tests"
    key: "gpu_jra55_tests"
    env:
      TEST_GROUP: "jra55"
      GPU_TEST: "true"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 32G
      slurm_gpus: 1
      slurm_cpus_per_task: 8
      slurm_ntasks: 1
      slurm_gpus_per_task: 1

  - label: "GPU ECCO tests"
    key: "gpu_ecco_tests"
    env:
      TEST_GROUP: "ecco"
      GPU_TEST: "true"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 32G
      slurm_gpus: 1
      slurm_cpus_per_task: 8
      slurm_ntasks: 1
      slurm_gpus_per_task: 1
      
  - label: "GPU surface flux tests"
    key: "gpu_fluxes_tests"
    env:
      TEST_GROUP: "fluxes"
      GPU_TEST: "true"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 32G
      slurm_gpus: 1
      slurm_cpus_per_task: 8
      slurm_ntasks: 1
      slurm_gpus_per_task: 1
      
  - label: "GPU bathyemtry tests"
    key: "gpu_bathymetry_tests"
    env:
      TEST_GROUP: "bathymetry"
      GPU_TEST: "true"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 32G
      slurm_gpus: 1
      slurm_cpus_per_task: 8
      slurm_ntasks: 1
      slurm_gpus_per_task: 1
      
  - wait: ~
    continue_on_failure: true
