agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_05_27

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"

steps:
  - label: "initialize"
    key: "init"
    command:
      - "echo '--- Instantiate project'"
      - "julia --project -e 'using Pkg; Pkg.instantiate(; verbose=true); Pkg.precompile(; strict=true)'"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"

    agents:
      slurm_mem: 32G
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: "Run JRA55 tests"
    key: "tests_jra55"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
      TEST_GROUP: "jra55"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"

  - label: "Run ECCO2 tests"
    key: "tests_ecco2"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
      TEST_GROUP: "ecco2"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"

  - label: "documentation"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
      JULIA_DEBUG: "Documenter"
      # TMPDIR: "$TARTARUS_HOME/tmp"
    commands:
      - "julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'"
      - "julia --color=yes --project=docs/ docs/make.jl"
      
  - wait: ~
    continue_on_failure: true
