agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_05_27

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_DEBUG: "Documenter"
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0

steps:
  - label: "initialize"
    key: "init"
    command:
      - "echo '--- Instantiate project'"
      - "julia --project -e 'using Pkg; Pkg.instantiate(; verbose=true); Pkg.precompile(; strict=true)'"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"

    agents:
      slurm_mem: 32G
      slurm_cpus_per_task: 8
      slurm_gpus: 1
      slurm_ntasks: 1
      slurm_gpus_per_task: 1
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: "Run JRA55 tests"
    key: "tests_jra55"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
      TEST_GROUP: "jra55"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"

  - label: "Run ECCO tests"
    key: "tests_ecco"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
      TEST_GROUP: "ecco"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"

  - label: "Run surface flux tests"
    key: "tests_fluxes"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
      TEST_GROUP: "fluxes"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"

  - label: "Run documentation"
    key: "build_documentation"
    env:
      CUDA_VISIBLE_DEVICES: "0"
    commands:
      - "julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'"
      - "julia --color=yes --project=docs/ docs/make.jl"

  - wait: ~
    continue_on_failure: true
