agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_05_27

timeout_in_minutes: 1440

env:
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_NUM_PRECOMPILE_TASKS: 8

steps:
  - label: "initialize"
    key: "init"
    command:
      - "echo '--- Instantiate project'"
      - "julia --project -e 'using Pkg; Pkg.instantiate(verbose=true)'"
      - "echo '--- Precompile project'"
      - "julia --project -e 'using Pkg; Pkg.precompile(strict=true)'"
      # Force the initialization of the CUDA runtime as it is lazily loaded by default:
      - "echo '--- Force initialization of the CUDA runtime'"
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"
    agents:
      slurm_mem: 120G
      slurm_gpus: 1
      slurm_cpus_per_task: 8

  - wait

  - label: "Run JRA55 tests"
    key: "test_jra55"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
      TEST_GROUP: "jra55"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"

  - label: "Run ECCO tests"
    key: "test_ecco"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
      TEST_GROUP: "ecco"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"

  - label: "Run surface flux tests"
    key: "test_fluxes"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
      TEST_GROUP: "fluxes"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"

  - label: "Run simulation tests"
    key: "test_simulations"
    env:
      TEST_GROUP: "simulations"
    commands:
      - "julia --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 120G
      slurm_gpus: 1
      slurm_cpus_per_task: 8

  - wait: ~
    continue_on_failure: true

